### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sptinik** [HackerCalico/Magic_C2#5]
Could you make a video showing how to install the c2 and loader, it would be easier to understand

**Comment by HackerCalico** [comment]
Of course, but as you can see from other issues, there are currently some bugs and code that needs to be optimized, and I'm working on an update with a much changed version coming soon.

**Comment by sptinik** [comment]
![Captura de tela 2024-07-25 001708](https://github.com/user-attachments/assets/cf981330-b364-4e96-bf39-56804e4bb4ca)

- [ ]

**Comment by sptinik** [comment]
I have this problem, if you have Telegram

**Comment by HackerCalico** [comment]
I'm sorry to see this question again, I honestly don't know why this is happening, but I will adopt a more accurate approach in the new version.
If you are in a hurry, you can compile and run "Shell\HttpReverseShell\HttpReverseShell.sln" directly.
There is also a need to "pip install capstone" to call the plug-in. It is said that there will still be problems after installation. I will also use a more accurate method in the next version.
Because I had no problem running it on my own computer, I was actually shocked.

**Comment by sptinik** [comment]
What is your telegram?

**Comment by HackerCalico** [comment]
I'm sorry, it's not convenient for me. Does 1.0.0 have the same problems as before? I added an environmental check.
